import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Nav from "@/app/components/Nav";
import {FilmProvider} from "@/app/context/FilmContext";
import Notifications from "@/app/components/Notifications";
import {ThemeProvider} from "@/app/context/ThemeContext";
import {ThemeWrapper} from "@/app/components/ThemeWrapper";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
        <body>
        <ThemeProvider>
            <FilmProvider>
                <ThemeWrapper>
                    <Notifications />
                    <Nav/>
                    {children}
                </ThemeWrapper>
            </FilmProvider>
        </ThemeProvider>
        </body>
        </html>
    );
}
